package com.mbajdowski.ui;

import com.mbajdowski.encoder.DecodingException;
import com.mbajdowski.encoder.SteganographyEncoder;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Logger;

public class EncoderPanel {
    public final Logger LOGGER = Logger.getLogger(EncoderPanel.class.getName());

    public JPanel mainPanel;
    private JButton chooseImageButton;
    private JTabbedPane tabbedPanel;
    private JPanel uploadPanel;
    private JPanel textToImagePanel;
    private JPanel fileToImagePanel;
    private JPanel imageToTextPanel;
    private JPanel imageToFilePanel;
    private JLabel imagePathLabel;
    private JTextPane textPanel1;
    private JButton convertButton1;
    private JSlider bitsPerColorSlider;
    private JLabel availableBitsLabel;
    private JLabel bitsPerColorLabel;
    private JTextPane decodedMessageArea;
    private JButton decodeButton1;
    private JButton chooseFileButton;
    private JButton encodeFileButton;
    private JLabel filePathLabel;
    private JButton decodeFileButton;

    private BufferedImage providedImage;
    private File fileToEncode;
    private SteganographyEncoder steganographyEncoder;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public EncoderPanel() {
        enableComponents(false);

        chooseImageButton.addActionListener(e -> {
            JFileChooser jfc = new JFileChooser();
            jfc.addChoosableFileFilter(new FileNameExtensionFilter("Images", "png"));
            jfc.setCurrentDirectory(new File(System.getProperty("user.home") + "\\Desktop"));
            int returnValue = jfc.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                String path = jfc.getSelectedFile().getAbsolutePath();
                imagePathLabel.setText(path);
                try {
                    providedImage = ImageIO.read(new File(path));
                    int bitsPerColor = getNormalizedBitsFromColor();
                    steganographyEncoder = new SteganographyEncoder(providedImage, bitsPerColor);
                    availableBitsLabel.setText(Integer.toString(steganographyEncoder.getMaxNoOfBytes()));

                    enableComponents(true);
                } catch (IOException e1) {
                    JOptionPane.showMessageDialog(
                            mainPanel,
                            "Error while uploading image file",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    enableComponents(false);
                    imagePathLabel.setText("");
                    e1.printStackTrace();
                }
            }
        });

        bitsPerColorSlider.addChangeListener(e -> {
            bitsPerColorLabel.setText(Integer.toString(bitsPerColorSlider.getValue()));
            steganographyEncoder.setBitsFromColor(getNormalizedBitsFromColor());
            availableBitsLabel.setText(Integer.toString(steganographyEncoder.getMaxNoOfBytes()));
        });

        convertButton1.addActionListener(e -> {
            try {
                BufferedImage encodedImage = steganographyEncoder.encodeString(textPanel1.getText());
                ImageIO.write(encodedImage, "png", new File(generatePathOfNewFile()));
                JOptionPane.showMessageDialog(
                        mainPanel,
                        "Successfully encoded file. \n",
                        "Info",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (IllegalArgumentException | IOException e1) {
                JOptionPane.showMessageDialog(
                        mainPanel,
                        "Error while encoding text to file. \n" + e1.toString(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                e1.printStackTrace();
            }
        });

        decodeButton1.addActionListener(e -> {
            try {
                String decodedMessage = steganographyEncoder.decodeString();
                if (decodedMessage.isEmpty()) {
                    throw new Exception();
                }
                decodedMessageArea.setText(decodedMessage);
            } catch (Exception exc) {
                JOptionPane.showMessageDialog(
                        mainPanel,
                        "Error while decoding message!\nTry different number of bits.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        });

        chooseFileButton.addActionListener(e -> {
            JFileChooser jfc = new JFileChooser();
            jfc.setCurrentDirectory(new File(System.getProperty("user.home") + "\\Desktop"));
            int returnValue = jfc.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                String path = jfc.getSelectedFile().getAbsolutePath();
                filePathLabel.setText(path);
                fileToEncode = new File(path);
            }
        });

        encodeFileButton.addActionListener(e -> {
            try {
                if (!fileToEncode.exists()) {
                    JOptionPane.showMessageDialog(
                            mainPanel,
                            "Chosen file does not exist!",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
                BufferedImage encodedImage = steganographyEncoder.encodeFile(fileToEncode);
                ImageIO.write(encodedImage, "png", new File(generatePathOfNewFile()));
                JOptionPane.showMessageDialog(
                        mainPanel,
                        "Successfully encoded file. \n",
                        "Info",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e1) {
                JOptionPane.showMessageDialog(
                        mainPanel,
                        "Error while encoding the file!\nDetails: " + e1.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        });

        decodeFileButton.addActionListener(e -> {
            try {
                String path = System.getProperty("user.home") + "\\Desktop\\";
                steganographyEncoder.decodeFile(path);
                JOptionPane.showMessageDialog(
                        mainPanel,
                        "Successfully decoded file.\nFile stored in: " + path,
                        "Info",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (DecodingException e1) {
                JOptionPane.showMessageDialog(
                        mainPanel,
                        "Error while decoding file!\nTry different number of bits.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    private int getNormalizedBitsFromColor() {
        return (int) Math.pow(2, bitsPerColorSlider.getValue());
    }

    private String generatePathOfNewFile() {
        String oldPath = imagePathLabel.getText();
        String newPath = oldPath.substring(0, oldPath.length() - 4) + ".encoded.png";
        return newPath;
    }

    private void enableComponents(boolean enable) {
        enableComponent(tabbedPanel, enable);
        bitsPerColorSlider.setEnabled(enable);
    }

    private void enableComponent(Component component, boolean enable) {
        if (component instanceof JComponent) {
            for (Component c : ((JComponent) component).getComponents()) {
                if (c instanceof JComponent) {
                    enableComponent(c, enable);
                } else {
                    c.setEnabled(enable);
                }
            }
            component.setEnabled(enable);
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setMinimumSize(new Dimension(600, 300));
        mainPanel.setPreferredSize(new Dimension(600, 300));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
        uploadPanel = new JPanel();
        uploadPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(uploadPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                                    com.intellij.uiDesigner.core
                                                                                            .GridConstraints
                                                                                            .ANCHOR_NORTH,
                                                                                    com.intellij.uiDesigner.core
                                                                                            .GridConstraints
                                                                                            .FILL_HORIZONTAL,
                                                                                    com.intellij.uiDesigner.core
                                                                                            .GridConstraints
                                                                                            .SIZEPOLICY_CAN_SHRINK |
                                                                                            com.intellij.uiDesigner
                                                                                                    .core
                                                                                                    .GridConstraints
                                                                                                    .SIZEPOLICY_CAN_GROW,
                                                                                    1, null, null, null, 0, false));
        chooseImageButton = new JButton();
        chooseImageButton.setText("Choose image");
        uploadPanel.add(chooseImageButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                                            com.intellij.uiDesigner
                                                                                                    .core
                                                                                                    .GridConstraints
                                                                                                    .ANCHOR_WEST,
                                                                                            com.intellij.uiDesigner
                                                                                                    .core
                                                                                                    .GridConstraints
                                                                                                    .FILL_NONE,
                                                                                            1, 1, null, null, null, 0,
                                                                                            false));
        imagePathLabel = new JLabel();
        imagePathLabel.setText("Label");
        uploadPanel.add(imagePathLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1,
                                                                                         com.intellij.uiDesigner.core
                                                                                                 .GridConstraints
                                                                                                 .ANCHOR_WEST,
                                                                                         com.intellij.uiDesigner.core
                                                                                                 .GridConstraints
                                                                                                 .FILL_NONE,
                                                                                         com.intellij.uiDesigner.core
                                                                                                 .GridConstraints
                                                                                                 .SIZEPOLICY_WANT_GROW,
                                                                                         1, null, null, null, 0,
                                                                                         false));
        tabbedPanel = new JTabbedPane();
        mainPanel.add(tabbedPanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1,
                                                                                    com.intellij.uiDesigner.core
                                                                                            .GridConstraints
                                                                                            .ANCHOR_CENTER,
                                                                                    com.intellij.uiDesigner.core
                                                                                            .GridConstraints.FILL_BOTH,
                                                                                    com.intellij.uiDesigner.core
                                                                                            .GridConstraints
                                                                                            .SIZEPOLICY_CAN_SHRINK |
                                                                                            com.intellij.uiDesigner
                                                                                                    .core
                                                                                                    .GridConstraints
                                                                                                    .SIZEPOLICY_CAN_GROW,
                                                                                    com.intellij.uiDesigner.core
                                                                                            .GridConstraints
                                                                                            .SIZEPOLICY_CAN_SHRINK |
                                                                                            com.intellij.uiDesigner
                                                                                                    .core
                                                                                                    .GridConstraints
                                                                                                    .SIZEPOLICY_WANT_GROW,
                                                                                    null, new Dimension(200, 200), null,
                                                                                    0, false));
        textToImagePanel = new JPanel();
        textToImagePanel
                .setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPanel.addTab("text->img", textToImagePanel);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        textToImagePanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .ANCHOR_CENTER,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .FILL_BOTH,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_CAN_SHRINK
                                                                                              | com.intellij
                                                                                              .uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_CAN_GROW,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_CAN_SHRINK
                                                                                              | com.intellij
                                                                                              .uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_CAN_GROW,
                                                                                      null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                            com.intellij.uiDesigner.core
                                                                                    .GridConstraints.ANCHOR_CENTER,
                                                                            com.intellij.uiDesigner.core
                                                                                    .GridConstraints.FILL_BOTH,
                                                                            com.intellij.uiDesigner.core
                                                                                    .GridConstraints
                                                                                    .SIZEPOLICY_CAN_SHRINK | com
                                                                                    .intellij.uiDesigner.core
                                                                                    .GridConstraints
                                                                                    .SIZEPOLICY_CAN_GROW,
                                                                            com.intellij.uiDesigner.core
                                                                                    .GridConstraints
                                                                                    .SIZEPOLICY_CAN_SHRINK | com
                                                                                    .intellij.uiDesigner.core
                                                                                    .GridConstraints
                                                                                    .SIZEPOLICY_CAN_GROW,
                                                                            null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Number of available bytes:");
        panel2.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                            com.intellij.uiDesigner.core
                                                                                    .GridConstraints.ANCHOR_EAST,
                                                                            com.intellij.uiDesigner.core
                                                                                    .GridConstraints.FILL_NONE,
                                                                            com.intellij.uiDesigner.core
                                                                                    .GridConstraints.SIZEPOLICY_FIXED,
                                                                            com.intellij.uiDesigner.core
                                                                                    .GridConstraints.SIZEPOLICY_FIXED,
                                                                            null, null, null, 0, false));
        availableBitsLabel = new JLabel();
        availableBitsLabel.setText("0");
        panel2.add(availableBitsLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1,
                                                                                        com.intellij.uiDesigner.core
                                                                                                .GridConstraints
                                                                                                .ANCHOR_WEST,
                                                                                        com.intellij.uiDesigner.core
                                                                                                .GridConstraints
                                                                                                .FILL_NONE,
                                                                                        com.intellij.uiDesigner.core
                                                                                                .GridConstraints
                                                                                                .SIZEPOLICY_FIXED,
                                                                                        com.intellij.uiDesigner.core
                                                                                                .GridConstraints
                                                                                                .SIZEPOLICY_FIXED,
                                                                                        null, null, null, 0, false));
        convertButton1 = new JButton();
        convertButton1.setText("Encode Text");
        textToImagePanel.add(convertButton1, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1,
                                                                                              com.intellij.uiDesigner
                                                                                                      .core
                                                                                                      .GridConstraints.ANCHOR_CENTER,
                                                                                              com.intellij.uiDesigner
                                                                                                      .core
                                                                                                      .GridConstraints.FILL_HORIZONTAL,
                                                                                              com.intellij.uiDesigner
                                                                                                      .core
                                                                                                      .GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                              com.intellij.uiDesigner
                                                                                                      .core
                                                                                                      .GridConstraints.SIZEPOLICY_FIXED,
                                                                                              null, null, null, 0,
                                                                                              false));
        final JLabel label2 = new JLabel();
        label2.setText("Message to encode:");
        textToImagePanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .ANCHOR_WEST,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .FILL_NONE,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_FIXED,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_FIXED,
                                                                                      null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        textToImagePanel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1,
                                                                                           com.intellij.uiDesigner
                                                                                                   .core
                                                                                                   .GridConstraints
                                                                                                   .ANCHOR_CENTER,
                                                                                           com.intellij.uiDesigner
                                                                                                   .core
                                                                                                   .GridConstraints
                                                                                                   .FILL_BOTH,
                                                                                           com.intellij.uiDesigner
                                                                                                   .core
                                                                                                   .GridConstraints
                                                                                                   .SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                           com.intellij.uiDesigner
                                                                                                   .core
                                                                                                   .GridConstraints
                                                                                                   .SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                           null, null, null, 0, false));
        textPanel1 = new JTextPane();
        textPanel1.setText("");
        scrollPane1.setViewportView(textPanel1);
        fileToImagePanel = new JPanel();
        fileToImagePanel
                .setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPanel.addTab("file->img", fileToImagePanel);
        final JLabel label3 = new JLabel();
        label3.setText("File to be encoded:");
        fileToImagePanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .ANCHOR_WEST,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .FILL_NONE,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_FIXED,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_FIXED,
                                                                                      null, null, null, 0, false));
        encodeFileButton = new JButton();
        encodeFileButton.setText("Encode File");
        fileToImagePanel.add(encodeFileButton, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1,
                                                                                                com.intellij
                                                                                                        .uiDesigner
                                                                                                        .core
                                                                                                        .GridConstraints.ANCHOR_CENTER,
                                                                                                com.intellij
                                                                                                        .uiDesigner
                                                                                                        .core
                                                                                                        .GridConstraints.FILL_HORIZONTAL,
                                                                                                com.intellij
                                                                                                        .uiDesigner
                                                                                                        .core
                                                                                                        .GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                                com.intellij
                                                                                                        .uiDesigner
                                                                                                        .core
                                                                                                        .GridConstraints.SIZEPOLICY_FIXED,
                                                                                                null, null, null, 0,
                                                                                                false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        fileToImagePanel.add(panel3, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .ANCHOR_CENTER,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .FILL_BOTH,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_CAN_SHRINK
                                                                                              | com.intellij
                                                                                              .uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_CAN_GROW,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_CAN_SHRINK
                                                                                              | com.intellij
                                                                                              .uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_CAN_GROW,
                                                                                      null, null, null, 0, false));
        chooseFileButton = new JButton();
        chooseFileButton.setText("Choose file");
        panel3.add(chooseFileButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .ANCHOR_WEST,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .FILL_NONE,
                                                                                      1,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_FIXED,
                                                                                      null, null, null, 0, false));
        filePathLabel = new JLabel();
        filePathLabel.setText("Label");
        panel3.add(filePathLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1,
                                                                                   com.intellij.uiDesigner.core
                                                                                           .GridConstraints
                                                                                           .ANCHOR_CENTER,
                                                                                   com.intellij.uiDesigner.core
                                                                                           .GridConstraints
                                                                                           .FILL_HORIZONTAL,
                                                                                   com.intellij.uiDesigner.core
                                                                                           .GridConstraints
                                                                                           .SIZEPOLICY_WANT_GROW,
                                                                                   com.intellij.uiDesigner.core
                                                                                           .GridConstraints
                                                                                           .SIZEPOLICY_FIXED,
                                                                                   null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        fileToImagePanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1,
                                                                                       com.intellij.uiDesigner.core
                                                                                               .GridConstraints
                                                                                               .ANCHOR_CENTER,
                                                                                       com.intellij.uiDesigner.core
                                                                                               .GridConstraints
                                                                                               .FILL_VERTICAL,
                                                                                       1,
                                                                                       com.intellij.uiDesigner.core
                                                                                               .GridConstraints
                                                                                               .SIZEPOLICY_WANT_GROW,
                                                                                       null, null, null, 0, false));
        imageToTextPanel = new JPanel();
        imageToTextPanel
                .setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPanel.addTab("img->txt", imageToTextPanel);
        final JLabel label4 = new JLabel();
        label4.setText("Encoded message:");
        imageToTextPanel.add(label4, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .ANCHOR_WEST,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .FILL_NONE,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_FIXED,
                                                                                      com.intellij.uiDesigner.core
                                                                                              .GridConstraints
                                                                                              .SIZEPOLICY_FIXED,
                                                                                      null, null, null, 0, false));
        decodeButton1 = new JButton();
        decodeButton1.setEnabled(true);
        decodeButton1.setText("Decode Text");
        imageToTextPanel.add(decodeButton1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1,
                                                                                             com.intellij.uiDesigner
                                                                                                     .core
                                                                                                     .GridConstraints
                                                                                                     .ANCHOR_CENTER,
                                                                                             com.intellij.uiDesigner
                                                                                                     .core
                                                                                                     .GridConstraints
                                                                                                     .FILL_HORIZONTAL,
                                                                                             com.intellij.uiDesigner
                                                                                                     .core
                                                                                                     .GridConstraints
                                                                                                     .SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                             com.intellij.uiDesigner
                                                                                                     .core
                                                                                                     .GridConstraints
                                                                                                     .SIZEPOLICY_FIXED,
                                                                                             null, null, null, 0,
                                                                                             false));
        final JScrollPane scrollPane2 = new JScrollPane();
        imageToTextPanel.add(scrollPane2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
                                                                                           com.intellij.uiDesigner
                                                                                                   .core
                                                                                                   .GridConstraints
                                                                                                   .ANCHOR_CENTER,
                                                                                           com.intellij.uiDesigner
                                                                                                   .core
                                                                                                   .GridConstraints
                                                                                                   .FILL_BOTH,
                                                                                           com.intellij.uiDesigner
                                                                                                   .core
                                                                                                   .GridConstraints
                                                                                                   .SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                           com.intellij.uiDesigner
                                                                                                   .core
                                                                                                   .GridConstraints
                                                                                                   .SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                           null, null, null, 0, false));
        decodedMessageArea = new JTextPane();
        decodedMessageArea.setEditable(false);
        scrollPane2.setViewportView(decodedMessageArea);
        imageToFilePanel = new JPanel();
        imageToFilePanel
                .setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPanel.addTab("img->file", imageToFilePanel);
        decodeFileButton = new JButton();
        decodeFileButton.setText("Decode File");
        imageToFilePanel.add(decodeFileButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
                                                                                                com.intellij
                                                                                                        .uiDesigner
                                                                                                        .core
                                                                                                        .GridConstraints.ANCHOR_CENTER,
                                                                                                com.intellij
                                                                                                        .uiDesigner
                                                                                                        .core
                                                                                                        .GridConstraints.FILL_HORIZONTAL,
                                                                                                com.intellij
                                                                                                        .uiDesigner
                                                                                                        .core
                                                                                                        .GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                                com.intellij
                                                                                                        .uiDesigner
                                                                                                        .core
                                                                                                        .GridConstraints.SIZEPOLICY_FIXED,
                                                                                                null, null, null, 0,
                                                                                                false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        imageToFilePanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                                       com.intellij.uiDesigner.core
                                                                                               .GridConstraints
                                                                                               .ANCHOR_CENTER,
                                                                                       com.intellij.uiDesigner.core
                                                                                               .GridConstraints
                                                                                               .FILL_VERTICAL,
                                                                                       1,
                                                                                       com.intellij.uiDesigner.core
                                                                                               .GridConstraints
                                                                                               .SIZEPOLICY_WANT_GROW,
                                                                                       null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel4, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1,
                                                                               com.intellij.uiDesigner.core
                                                                                       .GridConstraints.ANCHOR_CENTER,
                                                                               com.intellij.uiDesigner.core
                                                                                       .GridConstraints.FILL_BOTH,
                                                                               com.intellij.uiDesigner.core
                                                                                       .GridConstraints
                                                                                       .SIZEPOLICY_CAN_SHRINK | com
                                                                                       .intellij.uiDesigner.core
                                                                                       .GridConstraints
                                                                                       .SIZEPOLICY_CAN_GROW,
                                                                               com.intellij.uiDesigner.core
                                                                                       .GridConstraints
                                                                                       .SIZEPOLICY_CAN_SHRINK | com
                                                                                       .intellij.uiDesigner.core
                                                                                       .GridConstraints
                                                                                       .SIZEPOLICY_CAN_GROW,
                                                                               null, null, null, 0, false));
        bitsPerColorSlider = new JSlider();
        bitsPerColorSlider.setMajorTickSpacing(1);
        bitsPerColorSlider.setMaximum(3);
        bitsPerColorSlider.setMinimum(0);
        bitsPerColorSlider.setMinorTickSpacing(1);
        bitsPerColorSlider.setPaintLabels(true);
        bitsPerColorSlider.setPaintTicks(true);
        bitsPerColorSlider.setPaintTrack(true);
        bitsPerColorSlider.setSnapToTicks(true);
        bitsPerColorSlider.setToolTipText("This is power of 2 value");
        bitsPerColorSlider.setValue(0);
        panel4.add(bitsPerColorSlider, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2,
                                                                                        com.intellij.uiDesigner.core
                                                                                                .GridConstraints
                                                                                                .ANCHOR_WEST,
                                                                                        com.intellij.uiDesigner.core
                                                                                                .GridConstraints
                                                                                                .FILL_HORIZONTAL,
                                                                                        com.intellij.uiDesigner.core
                                                                                                .GridConstraints
                                                                                                .SIZEPOLICY_WANT_GROW,
                                                                                        com.intellij.uiDesigner.core
                                                                                                .GridConstraints
                                                                                                .SIZEPOLICY_FIXED,
                                                                                        null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Bits per color (pow of 2):");
        panel4.add(label5, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                            com.intellij.uiDesigner.core
                                                                                    .GridConstraints.ANCHOR_EAST,
                                                                            com.intellij.uiDesigner.core
                                                                                    .GridConstraints.FILL_NONE,
                                                                            com.intellij.uiDesigner.core
                                                                                    .GridConstraints.SIZEPOLICY_FIXED,
                                                                            com.intellij.uiDesigner.core
                                                                                    .GridConstraints.SIZEPOLICY_FIXED,
                                                                            null, null, null, 0, false));
        bitsPerColorLabel = new JLabel();
        bitsPerColorLabel.setText("0");
        panel4.add(bitsPerColorLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1,
                                                                                       com.intellij.uiDesigner.core
                                                                                               .GridConstraints
                                                                                               .ANCHOR_WEST,
                                                                                       com.intellij.uiDesigner.core
                                                                                               .GridConstraints
                                                                                               .FILL_NONE,
                                                                                       com.intellij.uiDesigner.core
                                                                                               .GridConstraints
                                                                                               .SIZEPOLICY_FIXED,
                                                                                       com.intellij.uiDesigner.core
                                                                                               .GridConstraints
                                                                                               .SIZEPOLICY_FIXED,
                                                                                       null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() { return mainPanel; }
}